### ISSUE TITLE
Make a note on website regarding missing roles

### ISSUE THREAD

**Issue by lamepenguins** [adrianocola/spyfall#34]
The list of roles for the 2nd version of the game is incomplete. Many people are complaining that the code is bad on a popular video series on YouTube. Also, it would be great if there was information on how to contribute to the list with the official roles to those who actually own the game.

**Comment by adrianocola** [comment]
Hi again, @lamepenguins!

I added the project to [crowdin](https://crowdin.com/project/adrianocola-spyfall) to manage translations. It is easier for people to contribute with translations or add the missing locations!

About the code, I know it sucks 😅
The project started to be a simple pass-and-play version of spyfall (without rooms, sync, exports, etc). The file [index.js](https://github.com/adrianocola/spyfall/blob/c50bf9757813aecee31fba009f089a87c51f79ed/index.js) only had 335 lines back then. Then I started to add the other features without worrying about the code (just wanted to make it work). So it is working and I don't have the time to rewrite it ( I think I would use [react](https://facebook.github.io/react/) and host with [firebase](https://firebase.google.com), using their real-time DB). Maybe in my next vacations.

Can you please share the link of the video/channel you mentioned? I would like to know their opinion!

Thank you!

**Comment by roryokane** [comment]
The YouTube channel featuring your website is [Node](https://www.youtube.com/user/Node); it's how I found this repo too. They have many videos of themselves playing Spyfall 1 using a different website (http://spyfall.crabhat.com/). They have a [Spyfall playlist](https://www.youtube.com/playlist?list=PLQOB_yCwC5J3SzEX5zRJ2adV45eGRqCPO) but it doesn't include every single Spyfall video they made.

Starting a month ago they switched to playing Spyfall 2 using your website. They have four videos featuring it so far: [1], [2], [3], [4]. In the last few they were complaining about bugs and that the developers need to fix them. I can see from the code that most of the bugs were caused by missing role data, though I don't think all of them were.

[1]: https://www.youtube.com/watch?v=EHsXDNuKNRQ
[2]: https://www.youtube.com/watch?v=seNkDmdbRZs
[3]: https://www.youtube.com/watch?v=s8QDAiqLnWg
[4]: https://www.youtube.com/watch?v=cY2yjTCF9gY

**Comment by lamepenguins** [comment]
https://youtu.be/s8QDAiqLnWg?t=15m27s

Here is the most notable scene.

**Comment by adrianocola** [comment]
What would be the best approach?

- Repeat roles until each player have a role (keep current behavior)
- If the is not enough roles for the number of players, does not show roles at all (and say about it?)

**Comment by adrianocola** [comment]
What would be the best approach?

- Keep repeating roles until each player have one role (current behavior)
- If there ir not enough roles for the number of players, don't show roles at all ( leave a message about it)

**Comment by lamepenguins** [comment]
I think your code is pretty good. It actually rotates through the locations. I think the best solution is to put a big red banner instead of a footer text regarding this.

Also, to anyone who owns the physical version of the game, I am happy to add the roles to the code for you.

**Comment by adrianocola** [comment]
I added missing roles for the english version (got some from online pictures, Tabletop Simulator and made up some others roles)

If I got the official roles I'll add them later.

**Comment by roryokane** [comment]
@adrianocola:

> What would be the best approach?
>
> - Repeat roles until each player have a role (keep current behavior)

Oh, I see I misread the code when I wrote earlier that you could handle the case of more players than known roles better. Together, `getAvailableRoles` and `assignPlayersRoles` spread out the roles pretty evenly. I see that the spy is always assigned, then the known roles are assigned to a player once, and then if there are remaining players without roles each of them is given a random role.

I can see a possible improvement, but it's a small one. After all the roles are assigned once, it's possible for all the remaining assigned roles to be the same, which might look weird. It would be better to reset `availableRoles` at that point to ensure that the roles given are balanced between all players. But that would only have an effect on games with at least five players, and it wouldn't be noticeable unless games had many more players.
